exports.USER_CREATED = 'User created successfully.';
exports.USER_LIST_FETCH = 'Users fetch successfully.';
exports.USER_EXIST = 'User already exist!';
exports.USER_DELETE = 'User deleted successfully.';
exports.USER_DETAILS_UPDATED = 'User details update successfully.';
exports.USER_NOT_FOUND = 'User does not exist!';
exports.USER_FOUND = 'User found successfully!';
exports.NOT_VALID_EMAIL = 'Please enter valid email.';
exports.USER_ACTIVATED = 'User is activated.';
exports.PASSWORD_NOT_MATCH = 'Password does not match, Please try again!';
exports.SOMETHING_WENT_WRONG = 'Something went wrong, please try later.';
exports.LOGIN_INPUTS_REQUIRED = 'Email and Password are required to login.';
exports.FORBIDDEN_EMAIL = 'This email is forbidden!';
exports.EMAIL_REQUIRED = 'Email is required!';
exports.FIRST_NAME_REQUIRED = 'First name is required!';
exports.LAST_NAME_REQUIRED = 'Last name is required!';
exports.FIRST_NAME_ONLY_STRING_CONTAINS =
  'First name should contain only characters!';
exports.LAST_ONLY_STRING_CONTAINS = 'Last name should contain only characters!';
exports.TOKEN_REQUIRED = 'A token is required for authentication';
exports.TOKEN_EXPIRED = 'Token expired!';
exports.DOAMIN_NOT_ALLOWED = 'Domain in this email is not allowed!';
exports.MINIMUM_LENGTH = (data) => `Minimum length is ${data}`;
exports.MAXIMUM_LENGTH = (data) => `Maximum length is ${data}`;
